### ISSUE TITLE
Add empty project

### ISSUE THREAD

**Issue by anandkumarkparmar** [Be-Better-Programmer/Tic-Tac-Toe#1]
Please follow the below guidelines to accept the submission.

- [ ] Kotlin as a primary language
- [ ] Package name should be com.bebetterprogrammer.tictactoe
- [ ] Minimum API level should be 21.

**Comment by meetkparmar** [comment]
Hi @anandkumarkparmar,

Can I work on this issue?
Thanks in advance.

**Comment by anandkumarkparmar** [comment]
Sure. Go Ahead! @meetkparmar

**Comment by anandkumarkparmar** [comment]
@all-contributors please add @meetkparmar for code
