### ISSUE TITLE
Add Home Screen 

### ISSUE THREAD

**Issue by anandkumarkparmar** [Be-Better-Programmer/Tic-Tac-Toe#11]
- Design: [1.Home.png](https://github.com/Be-Better-Programmer/Tic-Tac-Toe/blob/master/design/v1.0/1.Home.png)
- Colors: 
1. Primary: "#0096C5"
2. Secondary: "#50E3C2"
3. White: "#FFFFFF"
- Other Assets/icons: You can ask me over the slack channel.

**Comment by meetkparmar** [comment]
Hi @anandkumarkparmar,

Can I work on this issue?
Thanks in advance.

**Comment by anandkumarkparmar** [comment]
Sure. @meetkparmar

**Comment by anandkumarkparmar** [comment]
Thanks, @meetkparmar. I have merged your PR.
