### ISSUE TITLE
Add VsFriendSetup Screen

### ISSUE THREAD

**Issue by anandkumarkparmar** [Be-Better-Programmer/Tic-Tac-Toe#12]
- Design: [7.VsFriendSetup.png](https://github.com/Be-Better-Programmer/Tic-Tac-Toe/blob/master/design/v1.0/7.VsFriendSetup.png)
- Colors:
Primary: "#0096C5"
Secondary: "#50E3C2"
White: "#FFFFFF"
- Other Assets/icons: You can ask me over the slack channel.

**Comment by UmangGoti** [comment]
can i go for this issue??

**Comment by anandkumarkparmar** [comment]
Sure @UmangGoti. Go ahead!
