### ISSUE TITLE
Add VsFriendPlay Screen

### ISSUE THREAD

**Issue by anandkumarkparmar** [Be-Better-Programmer/Tic-Tac-Toe#13]
- Design: [8.VsFriendPlay.png](https://github.com/Be-Better-Programmer/Tic-Tac-Toe/blob/master/design/v1.0/8.VsFriendPlay.png)
- Colors:
Primary: "#0096C5"
Secondary: "#50E3C2"
White: "#FFFFFF"
- Other Assets/icons: You can ask me over the slack channel.

**Note: Implementation should be generic enough, so we can use the same in VsTravisPlay too.**

**Comment by HAP28** [comment]
Hey @anandkumarkparmar  ...I want to contribute for this module. Can i?

**Comment by anandkumarkparmar** [comment]
Sure @HAP28.
