### ISSUE TITLE
Add Won/Tie/Lost Popup

### ISSUE THREAD

**Issue by anandkumarkparmar** [Be-Better-Programmer/Tic-Tac-Toe#14]
- Design: [9.VsFriendWon.png](https://github.com/Be-Better-Programmer/Tic-Tac-Toe/blob/master/design/v1.0/9.VsFriendWon.png) [10.VsFriendTie.png](https://github.com/Be-Better-Programmer/Tic-Tac-Toe/blob/master/design/v1.0/10.VsFriendTie.png)
- Colors:
Primary: "#0096C5"
Secondary: "#50E3C2"
White: "#FFFFFF"
- Other Assets/icons: You can ask me over the slack channel.

**Note: Implementation should be generic enough, so all three cases(won, tie and lost) can use the same implementation.**

**Comment by meetkparmar** [comment]
Hi @anandkumarkparmar,

Can I work on this issue?
Thanks in advance.

**Comment by anandkumarkparmar** [comment]
Go ahead. @meetkparmar
