### ISSUE TITLE
Add VsJarvisSetup Screen

### ISSUE THREAD

**Issue by meetkparmar** [Be-Better-Programmer/Tic-Tac-Toe#27]
- Design: [2. vsJarvisSetup](https://github.com/Be-Better-Programmer/Tic-Tac-Toe/blob/master/design/v1.0/2.VsJarvisSetup.png)
- Colors:
     Primary: "#0096C5"
     Secondary: "#50E3C2"
- Other Assets/icons: You can ask me over the slack channel.

**Comment by UmangGoti** [comment]
can i go for this issue??

**Comment by anandkumarkparmar** [comment]
Sure. Go ahead, @UmangGoti.
