### ISSUE TITLE
Share and Rate the app functionality 

### ISSUE THREAD

**Issue by anandkumarkparmar** [Be-Better-Programmer/Tic-Tac-Toe#46]
- Sharing can be done through any social media and we will share in "{Text} - {Link}" format.
- Rate button will take the user to the app on PlayStore.

**Comment by UmangGoti** [comment]
can I go for this issue??

**Comment by anandkumarkparmar** [comment]
Sure @UmangGoti. Go ahead. Propose the design on slack, before going to implement it.
